name: Deploy docs to Pages
on: [push, workflow_dispatch]
#on:
#  push:
#    tags:
#      - 'v**'
#  ## Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

## Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Build docs
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"
          make html -C ./docs
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './docs/build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4